### PR TITLE
wd version up

### PR DESCRIPTION
**Pull request by j0tunn**
There were a lot of fixes + better appium/selendroid support since wd@2.8:
https://github.com/admc/wd/blob/master/doc/release-notes.md

### CODE REVIEW

**Comment by j0tunn** [comment]
@mtscout6 @zzo what do you think?

**Comment by mtscout6** [comment]
LGTM

**Comment by zzo** [comment]
has this been run thru the karma integration tests? Otherwise lgtm.  And while you're mucking around in package.json can you also remove the deprecated 'peerDependency' block?  thx!

**Comment by j0tunn** [comment]
> has this been run thru the karma integration tests?

I tried this on my project with my tests: everything is ok. Or you talking about some sort of special-karma-test I don't know about?

**Comment by zzo** [comment]
ha I was talking about https://github.com/karma-runner/integration-tests but now I see there's not one for webdriver which is sad.  OK lgtm thx

**Comment by zzo** [comment]
this is now on npm as 1.0.3

**Comment by j0tunn** [comment]
thanks!

**Pull request merged**
