### PR TITLE
add remote host features

### PR DESCRIPTION
**Pull request by everedifice**
change url in launcher to remote test execution.

it can be applied desktop, mobile, etc...

it already use for my company.

### CODE REVIEW

**Comment by everedifice** [comment]
I signed it!

**Comment by zzo** [comment]
can you rebase please thanks!

**Comment by everedifice** [comment]
i signed it

**Comment by minhyeong-kim** [comment]
I signed it!

**Comment by everedifice** [comment]
I signed it!

**Comment by minhyeong-kim** [comment]
I signed it!

**Comment by everedifice** [comment]
@zzo Sorry to late reply. I rebase branch. but CLA check are hard to make it success.

"everedifice", "minhyeong-kim" are me. how do i to make CLA check success?

**Comment by everedifice** [comment]
I pull request later.

**Pull request closed without merging**
